const UPDATE_ASSET_LIST = 'UPDATE_ASSET_LIST';
const UPDATE_CRYPTO_ASSET = 'UPDATE_CRYPTO_ASSET';
const FETCHING_API_ASSETS = 'FETCHING_API_ASSETS';
const FETCHING_API_SUCCESS = 'FETCHING_API_SUCCESS';
const FETCHING_API_FAILURE = 'FETCHING_API_FAILURE';

export { 
    UPDATE_ASSET_LIST, UPDATE_CRYPTO_ASSET,
FETCHING_API_ASSETS, FETCHING_API_SUCCESS, FETCHING_API_FAILURE 
}